### ISSUE TITLE
CI failing on node-v4.x and iojs-v3.x

### ISSUE THREAD

**Issue by rmg** [strongloop/loopback-oracle-builder#1]
http://ci.strongloop.com/job/loopback-oracle-builder/

**Comment by loay** [comment]
Hi @rmg 
Is this issue resolved? I see the last 3 builds are success. 
Thanks.

**Comment by jannyHou** [comment]
The original failure was too long ago, let's close it after our new version with oracledb passes ci.

**Comment by superkhau** [comment]
Closing, CI for these version are passing now and failing due to other reasons. See #6
